version: '3.8'

services:
  flask-html2image-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
    volumes:
      - ./app:/app  # Mount the local app directory to the /app directory in the container
